[build-system]
requires = ["setuptools", "setuptools-git-versioning"]
build-backend = "setuptools.build_meta"

[project]
name = "taggedict"
description = "Tags-aware dictionary"
readme = "README.md"
keywords = ["dictionary", "tags"]
license = {text = "MIT License"}
version = "{tag}"
classifiers = [
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
]
dependencies = [
]

[tool.setuptools]
packages = ["taggedict"]

[tool.setuptools-git-versioning]
enabled = true
